# source 'http://ruby.taobao.org'
source 'https://gems.ruby-china.org'

# gem 'eventmachine'
# gem 'em-http-request'
# gem 'ruby-prof'
gem 'byebug'
gem 'capybara'
gem 'poltergeist'
gem 'selenium-webdriver'
